# Generated by Django 5.2.3 on 2025-07-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(max_length=500, verbose_name='content'),
        ),
    ]
