# Generated by Django 5.2.3 on 2025-07-12 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50, verbose_name='team name')),
                ('team_logo', models.ImageField(blank=True, default='images/fallback.png', null=True, upload_to='images/')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
