# Generated by Django 5.2.3 on 2025-07-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teams_about_alter_teams_captain_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='team name'),
        ),
    ]
