# Generated by Django 5.2.3 on 2025-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_newuser_is_captian_remove_newuser_is_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='profilePic',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to='images/'),
        ),
    ]
