# Generated by Django 5.2.3 on 2025-07-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newuser_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='profilePic',
            field=models.ImageField(blank=True, default='images/fallback.png', null=True, upload_to='images/'),
        ),
    ]
