# Generated by Django 5.2.3 on 2025-07-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueslots',
            name='slot_time',
            field=models.CharField(max_length=100),
        ),
    ]
