# Generated by Django 5.2.3 on 2025-07-15 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_alter_venueslots_slot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueslots',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='venues',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
