# Generated by Django 5.2.3 on 2025-07-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_venueslots_date_alter_venues_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueslots',
            name='slot_time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='venueslots',
            unique_together={('venue', 'date', 'slot_time')},
        ),
    ]
